# Generated by Django 4.2 on 2023-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_alter_locationitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationitem',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
