# Generated by Django 4.2 on 2023-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_alter_locationitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationitem',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
