# Generated by Django 4.2 on 2023-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0004_alter_locationitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
