# Generated by Django 5.0.1 on 2024-01-31 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0006_alter_locationbooking_primary_camp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationbooking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='locationbooking',
            name='start',
        ),
        migrations.AddField(
            model_name='locationbooking',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='locationbooking',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='locationbooking',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='locationbooking',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
