# Generated by Django 4.2 on 2023-08-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0004_sjakbooking_remarks_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjakitem',
            name='quantity_lager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sjakitem',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Sjak.sjakitemtype'),
        ),
    ]
