# Generated by Django 4.2 on 2023-08-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0006_alter_sjakitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjakitem',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
