# Generated by Django 4.2 on 2023-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0007_alter_sjakitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjakbooking',
            name='status_internal',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Afventer', max_length=10),
        ),
    ]
