# Generated by Django 4.2 on 2023-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0008_sjakbooking_status_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjakbooking',
            name='status_internal',
            field=models.CharField(choices=[('Afventer', 'Afventer'), ('Igang', 'Igang'), ('Klar', 'Klar'), ('Afsluttet', 'Afsluttet')], default='Afventer', max_length=10),
        ),
    ]
