# Generated by Django 4.2 on 2024-01-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_alter_event_deadline_aktivitetsteam_and_more'),
        ('Sjak', '0009_alter_sjakbooking_status_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjakbooking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.event'),
        ),
    ]
