# Generated by Django 4.2 on 2024-01-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0010_sjakbooking_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjakbooking',
            name='end',
            field=models.DateTimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='sjakbooking',
            name='start',
            field=models.DateTimeField(verbose_name='Start'),
        ),
    ]
