# Generated by Django 3.2.20 on 2024-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0011_alter_sjakbooking_end_alter_sjakbooking_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjakbooking',
            name='end_time',
            field=models.TimeField(default='12:00', verbose_name='Slut tidspunkt'),
        ),
        migrations.AddField(
            model_name='sjakbooking',
            name='start_time',
            field=models.TimeField(default='12:00', verbose_name='Start tidspunkt'),
        ),
        migrations.AlterField(
            model_name='sjakbooking',
            name='end',
            field=models.DateTimeField(verbose_name='Slut dato'),
        ),
        migrations.AlterField(
            model_name='sjakbooking',
            name='start',
            field=models.DateTimeField(verbose_name='Start dato'),
        ),
    ]
