# Generated by Django 5.0.1 on 2024-01-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0012_auto_20240116_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SjakItemType',
        ),
    ]
