# Generated by Django 5.0.1 on 2024-01-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0014_sjakitemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjakitem',
            name='test',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Sjak.sjakitemtype'),
        ),
    ]
