# Generated by Django 5.0.1 on 2024-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0016_rename_test_sjakitem_item_type_remove_sjakitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjakbooking',
            name='end',
            field=models.DateField(verbose_name='Slut dato'),
        ),
        migrations.AlterField(
            model_name='sjakbooking',
            name='start',
            field=models.DateField(verbose_name='Start dato'),
        ),
    ]
