# Generated by Django 5.0.1 on 2024-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0017_alter_sjakbooking_end_alter_sjakbooking_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjakbooking',
            name='end_time',
            field=models.TimeField(default='12:01', verbose_name='Slut tidspunkt'),
        ),
        migrations.AlterField(
            model_name='sjakbooking',
            name='start_time',
            field=models.TimeField(default='12:01', verbose_name='Start tidspunkt'),
        ),
    ]
