# Generated by Django 5.0.1 on 2024-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0018_alter_sjakbooking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjakitem',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sjakitem',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
