# Generated by Django 5.0.1 on 2024-11-02 13:52

import django.db.models.deletion
from django.db import migrations, models

def set_default_location(apps, schema_editor):
    SjakItem = apps.get_model('Sjak', 'SjakItem')
    default_location = apps.get_model('Sjak', 'SjakItemLocation').objects.first()
    if default_location:
        SjakItem.objects.filter(location__isnull=True).update(location=default_location)

class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0019_alter_sjakitem_description_alter_sjakitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SjakItemLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='sjakitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SjakItem/'),
        ),
        migrations.AlterField(
            model_name='sjakitem',
            name='item_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Sjak.sjakitemtype'),
        ),
        migrations.AddField(
            model_name='sjakitem',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sjak.sjakitemlocation'),
        ),
    ]
