# Generated by Django 4.2 on 2023-05-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
