# Generated by Django 4.2 on 2023-08-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_volunteer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='phone',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
