# Generated by Django 4.2 on 2024-01-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_event_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(through='organization.TeamEventMembership', to='organization.event'),
        ),
    ]
