# Generated by Django 4.2 on 2024-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_teameventmembership_team_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline_aktivitetsteam',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_foto',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_lokaler',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_mad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_sjak',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_sos',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_teknik',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
