# Generated by Django 4.2 on 2024-01-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_event_deadline_aktivitetsteam_event_deadline_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline_aktivitetsteam',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_foto',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_lokaler',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_mad',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_sjak',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_sos',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='deadline_teknik',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
