# Generated by Django 3.2.20 on 2024-01-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
    ]
