# Generated by Django 3.2.20 on 2024-01-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_remove_todo_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
