# Generated by Django 5.0.1 on 2024-03-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_alter_volunteer_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='teams',
            field=models.ManyToManyField(blank=True, through='organization.TeamMembership', to='organization.team'),
        ),
    ]
