# Generated by Django 5.0.1 on 2024-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_volunteer_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(db_index=True, through='organization.TeamEventMembership', to='organization.event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(blank=True, db_index=True, through='organization.EventMembership', to='organization.event'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='teams',
            field=models.ManyToManyField(blank=True, db_index=True, through='organization.TeamMembership', to='organization.team'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
