# Generated by Django 4.2 on 2023-08-21 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butikkenbooking',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='butikkenbooking',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='butikkenbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
