# Generated by Django 4.2 on 2023-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0002_alter_butikkenbooking_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butikkenitem',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='butikkenitemtype',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
