# Generated by Django 4.2 on 2023-08-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0003_alter_butikkenitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butikkenitem',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
