# Generated by Django 4.2 on 2023-08-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0004_alter_butikkenitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='butikkenitem',
            name='content_normal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='butikkenitem',
            name='content_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
