# Generated by Django 4.2 on 2023-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0009_mealbooking_friday_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='friday_breakfast',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Morgenmadspakke', 'Morgenmadspakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='friday_dinner',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Laver mad bestilt ved KØK', 'Laver mad bestilt ved KØK'), ('Dinner trans', 'Dinner trans'), ('DYI - Chili Con Carne med ris / Råkost', 'DYI - Chili Con Carne med ris / Råkost'), ('DYI - Ciabatta med kylling og bacon', 'DYI - Ciabatta med kylling og bacon'), ('DYI - Indisk Kartoffelcurry / Råkost', 'DYI - Indisk Kartoffelcurry / Råkost'), ('DYI - Jambalaya / Spidskålssalat', 'DYI - Jambalaya / Spidskålssalat'), ('DYI - Pasta kødsovs / Spidskålssalat', 'DYI - Pasta kødsovs / Spidskålssalat'), ('DYI - Svensk pølseret / Spidskålssalat', 'DYI - Svensk pølseret / Spidskålssalat'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='friday_lunch',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Frokostpakke', 'Frokostpakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='monday_breakfast',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Morgenmadspakke', 'Morgenmadspakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='monday_dinner',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Laver mad bestilt ved KØK', 'Laver mad bestilt ved KØK'), ('Dinner trans', 'Dinner trans'), ('DYI - Chili Con Carne med ris / Råkost', 'DYI - Chili Con Carne med ris / Råkost'), ('DYI - Ciabatta med kylling og bacon', 'DYI - Ciabatta med kylling og bacon'), ('DYI - Indisk Kartoffelcurry / Råkost', 'DYI - Indisk Kartoffelcurry / Råkost'), ('DYI - Jambalaya / Spidskålssalat', 'DYI - Jambalaya / Spidskålssalat'), ('DYI - Pasta kødsovs / Spidskålssalat', 'DYI - Pasta kødsovs / Spidskålssalat'), ('DYI - Svensk pølseret / Spidskålssalat', 'DYI - Svensk pølseret / Spidskålssalat'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='monday_lunch',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Frokostpakke', 'Frokostpakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='thursday_breakfast',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Morgenmadspakke', 'Morgenmadspakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='thursday_dinner',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Laver mad bestilt ved KØK', 'Laver mad bestilt ved KØK'), ('Dinner trans', 'Dinner trans'), ('DYI - Chili Con Carne med ris / Råkost', 'DYI - Chili Con Carne med ris / Råkost'), ('DYI - Ciabatta med kylling og bacon', 'DYI - Ciabatta med kylling og bacon'), ('DYI - Indisk Kartoffelcurry / Råkost', 'DYI - Indisk Kartoffelcurry / Råkost'), ('DYI - Jambalaya / Spidskålssalat', 'DYI - Jambalaya / Spidskålssalat'), ('DYI - Pasta kødsovs / Spidskålssalat', 'DYI - Pasta kødsovs / Spidskålssalat'), ('DYI - Svensk pølseret / Spidskålssalat', 'DYI - Svensk pølseret / Spidskålssalat'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='thursday_lunch',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Frokostpakke', 'Frokostpakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='tuesday_breakfast',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Morgenmadspakke', 'Morgenmadspakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='tuesday_dinner',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Laver mad bestilt ved KØK', 'Laver mad bestilt ved KØK'), ('Dinner trans', 'Dinner trans'), ('DYI - Chili Con Carne med ris / Råkost', 'DYI - Chili Con Carne med ris / Råkost'), ('DYI - Ciabatta med kylling og bacon', 'DYI - Ciabatta med kylling og bacon'), ('DYI - Indisk Kartoffelcurry / Råkost', 'DYI - Indisk Kartoffelcurry / Råkost'), ('DYI - Jambalaya / Spidskålssalat', 'DYI - Jambalaya / Spidskålssalat'), ('DYI - Pasta kødsovs / Spidskålssalat', 'DYI - Pasta kødsovs / Spidskålssalat'), ('DYI - Svensk pølseret / Spidskålssalat', 'DYI - Svensk pølseret / Spidskålssalat'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='tuesday_lunch',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Frokostpakke', 'Frokostpakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='wednesday_breakfast',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Morgenmadspakke', 'Morgenmadspakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='wednesday_dinner',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Laver mad bestilt ved KØK', 'Laver mad bestilt ved KØK'), ('Dinner trans', 'Dinner trans'), ('DYI - Chili Con Carne med ris / Råkost', 'DYI - Chili Con Carne med ris / Råkost'), ('DYI - Ciabatta med kylling og bacon', 'DYI - Ciabatta med kylling og bacon'), ('DYI - Indisk Kartoffelcurry / Råkost', 'DYI - Indisk Kartoffelcurry / Råkost'), ('DYI - Jambalaya / Spidskålssalat', 'DYI - Jambalaya / Spidskålssalat'), ('DYI - Pasta kødsovs / Spidskålssalat', 'DYI - Pasta kødsovs / Spidskålssalat'), ('DYI - Svensk pølseret / Spidskålssalat', 'DYI - Svensk pølseret / Spidskålssalat'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='wednesday_lunch',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Spiser inde ', 'Spiser inde '), ('Frokostpakke', 'Frokostpakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
    ]
