# Generated by Django 5.0.1 on 2024-01-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0012_alter_butikkenbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butikkenbooking',
            name='start',
            field=models.DateTimeField(verbose_name='Start'),
        ),
    ]
