# Generated by Django 5.0.1 on 2024-02-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0013_alter_butikkenbooking_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealbooking',
            old_name='monday_breakfast',
            new_name='saturday_breakfast',
        ),
        migrations.RenameField(
            model_name='mealbooking',
            old_name='monday_dinner',
            new_name='saturday_dinner',
        ),
        migrations.RenameField(
            model_name='mealbooking',
            old_name='monday_lunch',
            new_name='saturday_lunch',
        ),
        migrations.RenameField(
            model_name='mealbooking',
            old_name='tuesday_breakfast',
            new_name='sunday_breakfast',
        ),
        migrations.RenameField(
            model_name='mealbooking',
            old_name='tuesday_lunch',
            new_name='sunday_lunch',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='tuesday_dinner',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='wednesday_breakfast',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='wednesday_dinner',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='wednesday_lunch',
        ),
        migrations.AddField(
            model_name='mealbooking',
            name='sunday_dinner',
            field=models.CharField(choices=[('Fællesforplejning', 'Fællesforplejning')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='friday_dinner',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Laver mad bestilt ved KØK', 'Laver mad bestilt ved KØK'), ('DYI - Chili Con Carne med ris / Råkost', 'DYI - Chili Con Carne med ris / Råkost'), ('DYI - Ciabatta med kylling og bacon', 'DYI - Ciabatta med kylling og bacon'), ('DYI - Indisk Kartoffelcurry / Råkost', 'DYI - Indisk Kartoffelcurry / Råkost'), ('DYI - Jambalaya / Spidskålssalat', 'DYI - Jambalaya / Spidskålssalat'), ('DYI - Pasta kødsovs / Spidskålssalat', 'DYI - Pasta kødsovs / Spidskålssalat'), ('DYI - Svensk pølseret / Spidskålssalat', 'DYI - Svensk pølseret / Spidskålssalat'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
    ]
