# Generated by Django 5.0.1 on 2024-02-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0014_rename_monday_breakfast_mealbooking_saturday_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealbooking',
            name='friday_lunch',
            field=models.CharField(choices=[('Vælg fra liste', 'Vælg fra liste'), ('Frokostpakke', 'Frokostpakke'), ('Står selv for forplejning', 'Står selv for forplejning')], default='none', max_length=200),
        ),
    ]
