# Generated by Django 5.0.1 on 2024-02-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0015_alter_mealbooking_friday_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butikkenbooking',
            name='start',
            field=models.DateField(verbose_name='Start'),
        ),
    ]
