# Generated by Django 5.0.1 on 2024-02-03 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0016_alter_butikkenbooking_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='butikkenbooking',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Start_time'),
            preserve_default=False,
        ),
    ]
