# Generated by Django 5.0.1 on 2024-02-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0018_butikkenbooking_for_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butikkenbooking',
            name='for_meal',
            field=models.CharField(choices=[('Aktivitet', 'Aktivitet'), ('Morgenmad', 'Morgenmad'), ('Frokost', 'Frokost'), ('Aftensmad', 'Aftensmad')], default='Pending', max_length=10),
        ),
    ]
