# Generated by Django 5.0.1 on 2024-08-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0020_mealplan_mealoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mealoption',
            name='name',
        ),
        migrations.AddField(
            model_name='mealoption',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Butikken.recipe'),
            preserve_default=False,
        ),
    ]
