# Generated by Django 5.0.1 on 2024-08-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0021_remove_mealoption_description_remove_mealoption_name_and_more'),
        ('organization', '0019_volunteer_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.mealoption')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.mealplan')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
            ],
            options={
                'unique_together': {('team', 'meal_plan')},
            },
        ),
    ]
