# Generated by Django 5.0.1 on 2024-08-19 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0022_teammealplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammealplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='friday_breakfast',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='friday_dinner',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='friday_lunch',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='saturday_breakfast',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='saturday_dinner',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='saturday_lunch',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='sunday_breakfast',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='sunday_dinner',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='sunday_lunch',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='thursday_breakfast',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='thursday_dinner',
        ),
        migrations.RemoveField(
            model_name='mealbooking',
            name='thursday_lunch',
        ),
        migrations.AddField(
            model_name='teammealplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammealplan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teammealplan',
            name='meal_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Butikken.mealbooking'),
        ),
        migrations.RemoveField(
            model_name='teammealplan',
            name='team',
        ),
    ]
