# Generated by Django 5.0.1 on 2024-08-23 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0023_alter_teammealplan_unique_together_and_more'),
        ('organization', '0019_volunteer_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammealplan',
            name='meal_booking',
        ),
        migrations.AddField(
            model_name='teammealplan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='teammealplan',
            name='team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='organization.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammealplan',
            name='team_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammealplan',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Butikken.mealoption'),
        ),
    ]
