# Generated by Django 5.0.1 on 2024-08-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0024_remove_teammealplan_meal_booking_teammealplan_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='butikkenbooking',
            options={'verbose_name': 'Butiksbestilling', 'verbose_name_plural': 'Butiksbestillinger'},
        ),
        migrations.AlterModelOptions(
            name='butikkenitem',
            options={'verbose_name': 'Butiksvare', 'verbose_name_plural': 'Butiksvarer'},
        ),
        migrations.AlterModelOptions(
            name='mealoption',
            options={'verbose_name': 'Måltidsvalgmulighed', 'verbose_name_plural': 'Måltidsvalgmulighedr'},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'verbose_name': 'Måltid', 'verbose_name_plural': 'Måltider'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Måltidspakke', 'verbose_name_plural': 'Måltidspakker'},
        ),
        migrations.AlterModelOptions(
            name='teammealplan',
            options={'verbose_name': 'Måltidsbestilling', 'verbose_name_plural': 'Måltidsbestillinger'},
        ),
    ]
