# Generated by Django 5.0.1 on 2024-08-27 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0025_alter_butikkenbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butikkenbooking',
            name='unit',
            field=models.CharField(default='A unit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
