# Generated by Django 5.0.1 on 2025-01-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0026_butikkenbooking_unit_alter_mealplan_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='butikkenbooking',
            name='date_used',
            field=models.DateField(blank=True, null=True, verbose_name='Dato brugt'),
        ),
    ]
