# Generated by Django 4.2 on 2023-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
