# Generated by Django 4.2 on 2023-08-21 22:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0002_alter_aktivitetsteambooking_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktivitetsteambooking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='aktivitetsteambooking',
            name='start',
        ),
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='location',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='remarks',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
