# Generated by Django 4.2 on 2023-09-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0004_aktivitetsteambooking_remarks_internal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteamitem',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
