# Generated by Django 4.2 on 2023-10-16 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AktivitetsTeam', '0005_alter_aktivitetsteamitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='assigned_aktivitetsteam',
            field=models.ManyToManyField(related_name='aktivitetsteam_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='team_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_contact_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
