# Generated by Django 4.2 on 2023-10-16 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AktivitetsTeam', '0006_aktivitetsteambooking_assigned_aktivitetsteam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='assigned_aktivitetsteam',
            field=models.ManyToManyField(related_name='Assigned_Aktivitetsteam', to=settings.AUTH_USER_MODEL),
        ),
    ]
