# Generated by Django 5.0.1 on 2024-02-03 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0007_alter_aktivitetsteambooking_assigned_aktivitetsteam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='assigned_aktivitetsteam',
            field=models.ManyToManyField(blank=True, related_name='Assigned_Aktivitetsteam', to=settings.AUTH_USER_MODEL),
        ),
    ]
