# Generated by Django 5.0.1 on 2024-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0009_aktivitetsteamitem_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='description_aktiverede',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='description_flow',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
