# Generated by Django 5.0.1 on 2024-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0010_aktivitetsteamitem_description_aktiverede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='description_eksempel',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
