# Generated by Django 5.0.1 on 2024-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0011_aktivitetsteamitem_description_eksempel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='latitude',
            field=models.FloatField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='longitude',
            field=models.FloatField(blank=True, default='1'),
            preserve_default=False,
        ),
    ]
