# Generated by Django 5.0.1 on 2024-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0012_aktivitetsteamitem_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktivitetsteamitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='aktivitetsteamitem',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='aktivitetsteamitem',
            name='longitude',
        ),
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='latitude',
            field=models.FloatField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aktivitetsteambooking',
            name='longitude',
            field=models.FloatField(blank=True, default='1'),
            preserve_default=False,
        ),
    ]
