# Generated by Django 5.0.1 on 2024-10-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0013_remove_aktivitetsteamitem_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='remarks',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
