# Generated by Django 5.0.1 on 2025-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0014_alter_aktivitetsteambooking_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AktivitetstTeamItem/'),
        ),
    ]
