# Generated by Django 4.2 on 2023-08-12 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teknik', '0004_teknikbooking_item_teknikbooking_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teknikbooking',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='teknikbooking',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
