# Generated by Django 4.2 on 2023-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teknik', '0005_teknikbooking_end_teknikbooking_start'),
    ]

    operations = [
    ]
