# Generated by Django 4.2 on 2023-08-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teknik', '0007_teknikbooking_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teknikbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
