# Generated by Django 4.2 on 2023-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teknik', '0008_alter_teknikbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teknikbooking',
            name='assistance_needed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='teknikbooking',
            name='delivery_needed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='teknikbooking',
            name='remarks_internal',
            field=models.TextField(blank=True),
        ),
    ]
