# Generated by Django 5.0.1 on 2024-08-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teknik', '0010_remove_teknikbooking_end_remove_teknikbooking_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teknikbooking',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='teknikbooking',
            name='latitude',
            field=models.FloatField(blank=True, default='56.114951'),
        ),
        migrations.AddField(
            model_name='teknikbooking',
            name='longitude',
            field=models.FloatField(blank=True, default='9.655592'),
        ),
    ]
