# Generated by Django 5.0.1 on 2024-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0003_remove_sosbooking_end_remove_sosbooking_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosbooking',
            name='dispatched',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='sosbooking',
            name='received',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
