# Generated by Django 4.2 on 2023-04-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('navn', models.CharField(max_length=30)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medarbejder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('navn', models.CharField(max_length=30)),
                ('telefon_nummer', models.CharField(max_length=8)),
                ('medarbejder_email', models.EmailField(default='email@address.dummy', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('navn', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('kursus', models.ManyToManyField(to='KursusOrganisation.kursus')),
                ('medarbejder', models.ManyToManyField(to='KursusOrganisation.medarbejder')),
            ],
        ),
    ]
