# Generated by Django 4.2 on 2023-04-09 15:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('KursusOrganisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medarbejder',
            name='telefon_nummer',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
