# Generated by Django 4.2 on 2023-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KursusOrganisation', '0002_medarbejder_telefon_nummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='medarbejder',
            name='medarbejder_email',
            field=models.EmailField(default='email@address.dummy', max_length=254),
        ),
        migrations.AlterField(
            model_name='medarbejder',
            name='telefon_nummer',
            field=models.CharField(max_length=8),
        ),
    ]
