# Generated by Django 4.2 on 2023-08-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depot', '0002_alter_depotbooking_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
