# Generated by Django 5.0.1 on 2024-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depot', '0006_alter_depotitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotbooking',
            name='end_time',
            field=models.TimeField(default='12:01', verbose_name='Slut tidspunkt'),
        ),
        migrations.AddField(
            model_name='depotbooking',
            name='start_time',
            field=models.TimeField(default='12:01', verbose_name='Start tidspunkt'),
        ),
        migrations.AlterField(
            model_name='depotbooking',
            name='end',
            field=models.DateField(verbose_name='Slut dato'),
        ),
        migrations.AlterField(
            model_name='depotbooking',
            name='start',
            field=models.DateField(verbose_name='Start dato'),
        ),
    ]
