# Generated by Django 4.2 on 2023-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoitem',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fotoitem',
            name='name',
            field=models.CharField(default='Old', max_length=100),
        ),
    ]
