# Generated by Django 4.2 on 2023-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0002_fotoitem_description_fotoitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotobooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
