# Generated by Django 4.2 on 2023-08-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0003_alter_fotobooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoitem',
            name='name',
            field=models.CharField(default='Item name', max_length=100),
        ),
    ]
