# Generated by Django 5.0.1 on 2024-08-28 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0004_alter_fotoitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotobooking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='fotobooking',
            name='start',
        ),
        migrations.AddField(
            model_name='fotobooking',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fotobooking',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fotobooking',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fotobooking',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
